version: "3.8"

networks:
  symfony-network:

services:
  db:
    image: postgres:13-alpine
    restart: always
    networks:
      - symfony-network
    environment:
        POSTGRES_PASSWORD: password
        POSTGRES_DB: db
        POSTGRES_USER: postgres
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
  php:
    container_name: php
    build:
      context: ./api
    volumes:
      - ./api:/var/www/api
    depends_on:
      - db
    networks:
      - symfony-network
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./api:/var/www/api
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
      - mailcatcher
    networks:
      - symfony-network
  vue:
    container_name: app
    build:
      context: ./app
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./app:/var/www/app
    working_dir: /var/www/app
    env_file:
      - ./.env
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1080:1080

volumes:
  db-data: {}