# Build and release.
name: Publish Docker image

#on:
  #release:
    #types: [published]
on: [push]


jobs:
  push_to_registry:
    name: Push Docker image build with docker-compose to Docker Hub
    runs-on: ubuntu-latest
    steps:
      # Check out source code.
    - name: Check out source code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # Build and push container build with docker 
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/bespectacled:latest
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
        