# Build and release.
name: Publish Docker image

#on:
  #release:
    #types: [published]
on: [push]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      # Check out source code.
    - name: Check out source code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push container image.
    - name: Build and push container image
      uses: docker/build-push-action@v3
      with:
        repository: ${{ secrets.DOCKER_USERNAME }}/bespectacled
        tag_with_ref: true
        tag_with_sha: true # sha-${GITHUB_SHA::7}
        push: true