name: Tests
on: [push]
jobs:
  php-unit-and-functional-tests:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./api
    strategy:
      fail-fast: true
      matrix:
        php-versions: ["8.1"]
    steps:
      - name: Create env file
        run: |
          touch .env
          echo "APP_ENV=${{secrets.APP_ENV}}" >> .env
          echo "APP_SECRET=${{secrets.APP_SECRET}}" >> .env
          echo "DATABASE_URL=${{secrets.DATABASE_URL}}" >> .env
          echo "JWT_SECRET=${{secrets.JWT_SECRET}}" >> .env
          echo "JWT_PASSPHRASE=${{secrets.JWT_PASSPHRASE}}" >> .env
          echo "JWT_SECRET_KEY=${{secrets.JWT_SECRET_KEY}}" >> .env
          echo "JWT_PUBLIC_KEY=${{secrets.JWT_PUBLIC_KEY}}" >> .env
          echo "CORS_ALLOW_ORIGIN=${{secrets.CORS_ALLOW_ORIGIN}}" >> .env
          echo "APP_NAME=${{secrets.APP_NAME}}" >> .env
          echo "APP_MAIL=${{secrets.APP_MAIL}}" >> .env
          echo "MAILER_DSN=${{secrets.MAILER_DSN}}" >> .env
          echo "MERCURE_URL=${{secrets.MERCURE_URL}}" >> .env
          echo "MERCURE_PUBLIC_URL=${{secrets.MERCURE_PUBLIC_URL}}" >> .env
          echo "MERCURE_JWT_SECRET=${{secrets.MERCURE_JWT_SECRET}}" >> .env
          echo "MAILER_DSN=${{secrets.MAILER_DSN}}" >> .env

      # —— Setup Github actions —————————————————————————————————————————————
      # https://github.com/actions/checkout (official)
      - name: Git checkout placeholder-service
        uses: actions/checkout@v2
      # https://github.com/shivammathur/setup-php (community)
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
          tools: composer:v2
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, iconv, json, mbstring, pdo
        env:
          update: true
      - name: Check PHP Version
        run: php -v
      # —— Composer —————————————————————————————————————————————————————————
      - name: Validate composer.json and composer.lock
        run: composer validate
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Allow plugin
        run: composer config --no-plugins allow-plugins.endroid/installer true
      - name: Install Composer dependencies
        run: composer install
      # —— Code style —— (Based on this package: https://github.com/OskarStark/php-cs-fixer-ga)
      - name: PHP-CS-Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --config=api/.php-cs-fixer.dist.php --allow-risky=yes
      ## —— Tests ———————————————————————————————————————————————————————————
      - name: Run functionnal and unit tests with PHPUNIT
        run: vendor/bin/simple-phpunit tests
      # —— Code coverage ————————————————————————————————————————————————————
      #- name: Upload coverage to Codecov
      # uses: codecov/codecov-action@v1
      # with:
      # token: ${{ secrets.CODECOV_TOKEN }}
      # file: ./api/coverage.xml
      # flags: unittests
      # name: codecov-umbrella
      #fail_ci_if_error: true
